# Generated by Django 3.0.4 on 2020-05-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilepicture',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
